
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  profiles:
    active: dev
  aop:
    proxy-target-class: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.jueke.entity
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  config: classpath:logback-spring.xml
###定义项目名称
server:
  context-path: /boot